### ISSUE TITLE
Only expose template variables in dev mode

### ISSUE THREAD

**Issue by ovenum** [animaux/kirby-devkit#1]
Hi @animaux just read your post in the Kirby Forum and took a quick look at the code.

It might be better to also check if Kirby is in [debug mode](https://getkirby.com/docs/reference/system/options/debug) and only expose the available template variables if this is case. You can check for debug mode with `kirby()->option()->debug() === true`.

People might create user accounts with limited or no panel access for their Kirby install. By appending the query variable these users could potentially see environment variables, api credentials, … which should not be exposed.

For reference
https://github.com/animaux/kirby-devkit/blob/82446549a541e06e2c7ff6687728409fbcd263f2/index.php#L14C1-L15C63

**Comment by animaux** [comment]
Good point, many thanks. Will add this!

**Comment by animaux** [comment]
Fixed in https://github.com/animaux/kirby-devkit/commit/49ae0391751cd7060249f26bb47fecd16ab10149
